version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.13

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            apk update && apk add --no-cache aws-cli

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

      # Your additional steps, e.g., Docker build and push to ECR
      - run:
          name: Build and push Docker image to ECR
          command: |
            docker build -t nginx:latest .

      # Trigger another CircleCI pipeline
      - run:
          name: Trigger Another Pipeline
          command: |
            apk --no-cache add curl git
            #curl -X POST -H "Content-Type: application/json" -d '{"branch":"main"}' -u "${d1f842c34d80ffaf0fb0973fd087234d32a2b0a3}:" https://circleci.com/api/v2/project/github/karthik7996/rapyder/pipeline
            #git clone git@github.com:karthik7996/nodjs_app.git
            ls
            git clone git@github.com:karthik7996/rapyder.git ~/my-app-frontend
            #git pull origin 'main'
            ls
            echo "hello"
            echo "$CIRCLE_BUILD_NUM"
            sed -i "s/tag: /tag: $CIRCLE_BUILD_NUM/g" ./vehicle/values.yaml"
            git add ./vehicle/values.yaml"
            git status
            git commit -m "CI/CD pipeline updated $CIRCLE_BUILD_NUM image to new image tag"
            #git config --global credential.helper cache'
            git push origin 'main'




