version: 2

defaults: &defaults
  working_directory: ~/my-app-backend
  docker:
    - image: docker:19.03.13

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Install AWS CLI and Configure Credentials
          command: |
            apk update && apk add --no-cache aws-cli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Build and push Docker image to ECR
          command: |
            aws s3 ls
            docker build -t nginx:latest .

  run_feature_tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-backend
      - add_ssh_keys:
          fingerprints:
            - "<here's the finger print>"
      - run:
          name: Install AWS CLI and Configure Credentials
          command: |
            apk update && apk add --no-cache aws-cli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Clone frontend repository
          command: >-
            apk --no-cache add git
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
            git clone git@github.com:karthik7996/rapyder.git ~/my-app-frontend
            ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - run_feature_tests
