version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.13

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t nginx:latest .


