version: 2.1

defaults: &defaults
  docker:
    - image: docker:19.03.13

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk --no-cache add git
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Install AWS CLI
          command: |
            apk update && apk add --no-cache aws-cli
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Build and push Docker image to ECR
          command: |
            aws s3 ls
            docker build -t nginx:latest .
            #git clone git@github.com:karthik7996/rapyder.git ~/my-app-frontend
            ls
  Update_menifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Menifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/karthik7996/rapyder.git
            ls
            cd rapyder
            ls -la
workflows:
  GitOpsflow:
    jobs:
      - build
      - Update_menifest:
          requires:
            - build           
