version: 2.1

defaults: &defaults
  docker:
    - image: docker:19.03.13

executors:
  scanner:
    docker:
      - image: openjdk:11    

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk --no-cache add git
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Install AWS CLI
          command: |
            apk update && apk add --no-cache aws-cli
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Build and push Docker image to ECR
          command: |
            aws s3 ls
            docker build -t nginx:latest .
            #git clone git@github.com:karthik7996/rapyder.git ~/my-app-frontend
            ls
  Update_menifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Menifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/karthik7996/rapyder.git
            #git clone https://$GITHUB_PERSONAL_TOKEN@github.com/karthik7996/jenkins_master-slave.git
            ls
            cd rapyder
            ls -la
            git config --global user.email "karthikraj9845@gmail.com"
            git config --global user.name "karthik"
            sed -i "s/tag: /tag: $CIRCLE_BUILD_NUM/" ./vehicle/values.yaml
            git add ./vehicle/values.yaml
            git status
            git commit -m "CI/CD pipeline updated $CIRCLE_BUILD_NUM image to new image tag"
            #git config --global credential.helper cache
            #git config --global http.postBuffer 524288000  # Set the buffer size to 500 MB (adjust as needed)
            #git config --global http.lowSpeedLimit 0       # Disable low-speed limit
            #git config --global http.lowSpeedTime 999999    # Set low-speed time limit to a large value
            git push -q https://$git@github.com/karthik7996/rapyder.git main
  commands:
  check-code-quality:
    description: Check Code Quality
    parameters:
      sonar_server_url:
        type: string
        description: "URL of your SonarQube server. e.g.: http://my.sonarqube,server:9000"
        default: http://15.206.124.28:9000/
      sonar_login:
        description: "Authentication key (sonar.login paramter) to access SonarQube and perform analysis"
        type: string
        default: f38b39900293cd841e3f663b23c18802739bbfcb
      sonar_sources:
        description: "Where the files are located?"
        type: string
        default: "$SONAR_SOURCES"            

          
workflows:
  GitOpsflow:
    jobs:
      - build
      - Update_menifest:
          requires:
            - build
            - commands
